### ISSUE TITLE
Apex 5?

### ISSUE THREAD

**Issue by Flake7811** [KarlHlmgrn/crypto-oled#2]
Hi there, I'm from the reddit post. You asked me to create an issue on the GitHub regarding this working on the Apex 5 :)

**Comment by KarlHlmgrn** [comment]
Please follow this tutorial but choose the Steelseries Apex 5: [https://www.youtube.com/watch?v=fXDTGba0l3w](url)
And then send the VID and PID of your Apex 5 keyboard in this thread.
