### ISSUE TITLE
Apex Pro - ghost keypress bugs when crypto-oled is running

### ISSUE THREAD

**Issue by palacinka** [KarlHlmgrn/crypto-oled#6]
oled crypto ticker works, but when python script  is running it is also causing weird ghost keypress bugs to the keyboard.
For example when crypto-oled  is running I no longer can select text  with ctrl+shift+alt +mouse pointer in sublime text
It is also randomly pressing CTRL key (tested with Aqua'S  Key Test). Or just portion of keys stops working completely. When I close  crypto-oled   keyboard no longer seem to have this issues.

**Comment by KarlHlmgrn** [comment]
A temporary solution can now be found under releases, [v3.3](https://github.com/KarlHlmgrn/crypto-oled/releases/tag/v3.3). Hopefully, this fixes your problems. If not try updating the keyboard module or by turning the hotkey off.
